# Site
repository: asdromundo/asdromundo.github.io
favicon: images/favicon.png

# Personal info
name: Antonio Sebastián Dromundo Escobedo
title: Computer Scientist
email: sebastiandromundo@outlook.com
phone: 
website: https://asdrome.digital/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: asdromundo
github_username:  asdromundo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: asdromundo
linkedin_username: asdromundo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Hola! Mi nombre es Antonio Sebastián, y soy un científico de la computación, ó computologo. ¿Qué es eso? Bueno, de la misma manera que existen ciencias que estudian al planeta Tierra, los fénomenos sociales y al ámbito de la salud, existe un área de estudio sobre las capacidades de las computadoras. No se trata de estudiar necesariamente tu laptop o la PC de sobremesa que tienes en tu escritorio, sí no de estudiar las maquinas teóricas que llevaron a crear lo que nosotros conocemos como computadoras. 
  
  - ***¿Qué problemas pueden ser resueltos con una computadora?*** Es una cuestión casi filosófica, después de todo, ni siquiera sabemos que problemas podemos resolver como humanos. 
  
  - ***¿Es una solución dada a un problema. la solución óptima?***. Éstas son cuestiones importantes para áreas como la Inteligencia Artificial, el aprendizaje de máquina ó el manejo de Big Data, pues todas ellas son aplicaciones directas de las Ciencias de la Computación.

#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#    - Lists
#    - Tables
#    - <a href="google.com">Links</a>
#    - Images

# Projects Section
projects_title: Proyectos #(Use this to override about projects section title)

# Experience Section
experience_title: Experiencia #(Use this to override about experience section title)

# Education Section
education_title: Educación #(Use this to override about education section title)

# More Section
more_title: Intereses #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
